export const SERVICE_CHARGE_PERCENTAGE = 7;
export const PESEWAS_PER_CEDI = 100;
export const REGISTRATION_FEE = 1_000;
export const PLATFORM_FEE_PERCENTAGE = 20;
export const DOCTOR_EARNINGS_PERCENTAGE = 80;
